version: "3"

services:

  price-alert-service:
    image: micheltank/price-alert-service
    container_name: price-alert-service
    build: ./price-alert-service
    env_file:
      - ./price-alert-service/env.example
    ports:
      - "8080:8080"
      - "8081:8081"
    extra_hosts:
      - "host.docker.internal:172.17.0.1"

  price-alert-job:
    image: micheltank/price-alert-job
    container_name: price-alert-job
    build: ./price-alert-job
    env_file:
      - ./price-alert-job/env.example
    extra_hosts:
      - "host.docker.internal:172.17.0.1"

  notification-service:
    image: micheltank/notification-service
    container_name: notification-service
    build: ./notification-service
    env_file:
      - ./notification-service/env.example
    extra_hosts:
      - "host.docker.internal:172.17.0.1"

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    extra_hosts:
      - "host.docker.internal:172.17.0.1"

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "9094:9094"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_LISTENERS: INTERNAL://:9092,OUTSIDE://:9094
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,OUTSIDE://host.docker.internal:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT
    extra_hosts:
      - "host.docker.internal:172.17.0.1"

  control-center:
    image: confluentinc/cp-enterprise-control-center:6.0.1
    hostname: control-center
    depends_on:
      - kafka
    ports:
      - "9021:9021"
    environment:
      CONTROL_CENTER_BOOTSTRAP_SERVERS: 'kafka:9092'
      CONTROL_CENTER_REPLICATION_FACTOR: 1
      CONTROL_CENTER_CONNECT_CLUSTER: http://kafka-connect:8083
      PORT: 9021
    extra_hosts:
      - "host.docker.internal:172.17.0.1"

  postgresql:
    image: postgres
    ports:
      - "5400:5432"
    environment:
      - POSTGRES_DB=crypto_price_alert
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./price-alert-service/pg_data:/var/lib/postgresql/data
    restart: always